sudo: false
jdk: oraclejdk8
language: android
android:
  components:
    # Using latest platform tools
    - tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_cache: rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew lintRelease testRelease

before_deploy:
  # Uploading to bintray all artifacts
  - ./gradlew bintrayUpload

deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: master
    tags: true
  script: echo Deployed

notifications:
  email: false
  slack: aol:M5cVriVZt6P4yiHdkH84N10l

